/**
 * useRealtimeOwner Hook - Production-Grade Real-Time Data
 * 
 * Features:
 * - Tenant Isolation: Each query uses where('restaurantId', '==', user.uid)
 * - Real-Time Calculation: Revenue is the mathematical sum of DELIVERED/PAID orders
 * - Smart Insights: Generated by algorithms based on real data, not mock text
 */

import { useState, useEffect } from 'react';
import { collection, query, where, onSnapshot, orderBy, Timestamp } from 'firebase/firestore';
import { db } from '../config/firebase';
import { useAuth } from './useAuth';
import { startOfDay, isSameDay, subDays } from 'date-fns';

// ══════════════════════════════════════════════════════════════════
// TYPES
// ══════════════════════════════════════════════════════════════════

export interface OwnerStats {
  salesToday: number;
  ordersToday: number;
  avgTicket: number;
  growth: number; // Percentage compared to yesterday
  salesYesterday: number;
}

export interface OperationalInsight {
  id: string;
  type: 'URGENT' | 'OPPORTUNITY' | 'INFO' | 'SUCCESS';
  title: string;
  desc: string;
  icon?: string;
  action?: () => void;
}

// ══════════════════════════════════════════════════════════════════
// HOOK
// ══════════════════════════════════════════════════════════════════

export function useRealtimeOwner() {
  const { user } = useAuth();
  const [stats, setStats] = useState<OwnerStats>({
    salesToday: 0,
    ordersToday: 0,
    avgTicket: 0,
    growth: 0,
    salesYesterday: 0
  });
  const [insights, setInsights] = useState<OperationalInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!user) {
      setLoading(false);
      return;
    }

    console.log('📊 [useRealtimeOwner] Subscribing to orders for:', user.uid);

    // Calculate date ranges
    const now = new Date();
    const todayStart = startOfDay(now);
    const yesterday = subDays(now, 1);
    const yesterdayStart = startOfDay(yesterday);

    // 1. REALTIME ORDERS SUBSCRIPTION
    // Fetch orders from the last 48 hours using restaurantId for tenant isolation
    const ordersQuery = query(
      collection(db, 'orders'),
      where('restaurantId', '==', user.uid),
      where('createdAt', '>=', Timestamp.fromDate(yesterdayStart)),
      orderBy('createdAt', 'desc')
    );

    const unsubOrders = onSnapshot(ordersQuery, (snapshot) => {
      let todayTotal = 0;
      let todayCount = 0;
      let yesterdayTotal = 0;
      let yesterdayCount = 0;

      snapshot.docs.forEach(doc => {
        const data = doc.data();
        
        // Handle createdAt - could be Timestamp or Date
        let orderDate: Date;
        if (data.createdAt?.toDate) {
          orderDate = data.createdAt.toDate();
        } else if (data.createdAt instanceof Date) {
          orderDate = data.createdAt;
        } else {
          orderDate = new Date(); // Fallback
        }

        // Only count REAL revenue: DELIVERED, PAID, or isPaid orders
        const isPaidOrder = 
          ['DELIVERED', 'delivered', 'PAID', 'paid'].includes(data.status) || 
          data.isPaid === true;

        if (isPaidOrder) {
          const orderTotal = Number(data.total) || 0;
          
          if (isSameDay(orderDate, now)) {
            todayTotal += orderTotal;
            todayCount += 1;
          } else if (isSameDay(orderDate, yesterday)) {
            yesterdayTotal += orderTotal;
            yesterdayCount += 1;
          }
        }
      });

      // Calculate growth percentage
      const growthPercent = yesterdayTotal > 0
        ? ((todayTotal - yesterdayTotal) / yesterdayTotal) * 100
        : todayTotal > 0 ? 100 : 0;

      // Calculate average ticket
      const avgTicket = todayCount > 0 ? todayTotal / todayCount : 0;

      const newStats: OwnerStats = {
        salesToday: todayTotal,
        ordersToday: todayCount,
        avgTicket,
        growth: growthPercent,
        salesYesterday: yesterdayTotal
      };

      setStats(newStats);

      // ════════════════════════════════════════════════════════════════
      // GENERATE REAL INSIGHTS (Algorithm-Based, Not Mock Text)
      // ════════════════════════════════════════════════════════════════
      const generatedInsights: OperationalInsight[] = [];

      // Insight 1: Daily Goal Progress
      if (todayTotal > 500 && todayTotal < 1000) {
        generatedInsights.push({
          id: 'goal-500',
          type: 'SUCCESS',
          title: 'Meta de R$ 500 atingida! 🎉',
          desc: `Você já vendeu ${formatCurrency(todayTotal)} hoje. Continue assim!`
        });
      } else if (todayTotal >= 1000) {
        generatedInsights.push({
          id: 'goal-1000',
          type: 'SUCCESS',
          title: 'Dia Excelente! 🔥',
          desc: `Faturamento de ${formatCurrency(todayTotal)} - acima da meta de R$ 1.000!`
        });
      }

      // Insight 2: Growth Alert
      if (growthPercent >= 20) {
        generatedInsights.push({
          id: 'growth-positive',
          type: 'OPPORTUNITY',
          title: 'Crescimento Expressivo',
          desc: `Vendas +${growthPercent.toFixed(0)}% em relação a ontem. Algo está funcionando!`
        });
      } else if (growthPercent <= -20 && yesterdayTotal > 0) {
        generatedInsights.push({
          id: 'growth-negative',
          type: 'URGENT',
          title: 'Queda nas Vendas',
          desc: `Vendas ${growthPercent.toFixed(0)}% abaixo de ontem. Considere uma promoção.`
        });
      }

      // Insight 3: Ticket Médio Analysis
      if (avgTicket > 0 && avgTicket < 30) {
        generatedInsights.push({
          id: 'low-ticket',
          type: 'INFO',
          title: 'Ticket Médio Baixo',
          desc: `Média de ${formatCurrency(avgTicket)} por pedido. Considere combos ou sugestões.`
        });
      } else if (avgTicket >= 80) {
        generatedInsights.push({
          id: 'high-ticket',
          type: 'SUCCESS',
          title: 'Ticket Médio Alto',
          desc: `Excelente! Média de ${formatCurrency(avgTicket)} por pedido.`
        });
      }

      // Insight 4: No sales alert
      if (todayCount === 0 && new Date().getHours() >= 11) {
        generatedInsights.push({
          id: 'no-sales',
          type: 'URGENT',
          title: 'Sem Vendas Hoje',
          desc: 'Ainda não houve pedidos confirmados hoje. Verifique se o cardápio está ativo.'
        });
      }

      setInsights(generatedInsights);
      setLoading(false);
      setError(null);

      console.log('✅ [useRealtimeOwner] Stats updated:', newStats);
    }, (err) => {
      console.error('❌ [useRealtimeOwner] Error:', err);
      setError(err.message);
      setLoading(false);
    });

    // Cleanup
    return () => {
      console.log('🔄 [useRealtimeOwner] Unsubscribing...');
      unsubOrders();
    };
  }, [user]);

  return { 
    stats, 
    insights, 
    loading, 
    error,
    hasData: stats.ordersToday > 0 || stats.salesYesterday > 0
  };
}

// Helper function
function formatCurrency(value: number): string {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL'
  }).format(value);
}

export default useRealtimeOwner;
