/**
 * Menu Types for Living Menu Feature
 * Firestore data model for digital restaurant menus
 */

// ══════════════════════════════════════════════════════════════════
// MENU ITEM - Individual dish/product
// ══════════════════════════════════════════════════════════════════

export interface MenuItem {
  id: string;
  title: string;
  description: string;
  price: number;
  imageUrl: string | null; // Generated by Emprata AI
  isHighlight: boolean;    // Featured in Stories carousel
}

// ══════════════════════════════════════════════════════════════════
// CATEGORY - Group of items (Entradas, Burgers, etc.)
// ══════════════════════════════════════════════════════════════════

export interface Category {
  id: string;
  title: string;
  items: MenuItem[];
}

// ══════════════════════════════════════════════════════════════════
// MENU - The complete digital menu
// ══════════════════════════════════════════════════════════════════

export interface Menu {
  id: string;
  ownerId: string;           // Firebase Auth UID
  slug: string;              // URL-friendly identifier (e.g., 'pizzaria-zico')
  name: string;              // Restaurant name
  description: string;       // Short description/tagline
  logoUrl: string | null;    // Restaurant logo
  phone: string;             // WhatsApp number (with country code)
  themeColor: string;        // Primary brand color (hex)
  categories: Category[];
  createdAt: Date;
  updatedAt: Date;
}

// ══════════════════════════════════════════════════════════════════
// AI ORGANIZATION RESPONSE
// ══════════════════════════════════════════════════════════════════

export interface AIOrganizeResponse {
  categories: {
    name: string;
    items: string[];
  }[];
  suggestedHighlights: string[];
}

// ══════════════════════════════════════════════════════════════════
// FORM DATA TYPES
// ══════════════════════════════════════════════════════════════════

export type MenuFormData = Omit<Menu, 'id' | 'createdAt' | 'updatedAt'>;

export interface NewMenuItem {
  title: string;
  description: string;
  price: number;
  imageUrl: string | null;
}
