/**
 * ⚡ NEURAL FEED - AI-Powered Dashboard Insights ⚡
 * Shows intelligent cards generated by Neural Core
 */

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  AlertTriangle, TrendingUp, Star, Lightbulb, 
  ChevronRight, X, RefreshCw, Sparkles
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { 
  NeuralInsight, 
  generateDailyInsights, 
  getMenuContext 
} from '../services/neuralCore';
import { getRecentLogs } from '../services/auditService';

// ══════════════════════════════════════════════════════════════════
// INSIGHT CARD COMPONENT
// ══════════════════════════════════════════════════════════════════

interface InsightCardProps {
  insight: NeuralInsight;
  onDismiss: (id: string) => void;
}

function InsightCard({ insight, onDismiss }: InsightCardProps) {
  const config = {
    anomaly: {
      icon: AlertTriangle,
      gradient: 'from-red-500/20 to-red-600/5',
      border: 'border-red-500/30',
      iconColor: 'text-red-400'
    },
    prediction: {
      icon: TrendingUp,
      gradient: 'from-blue-500/20 to-blue-600/5',
      border: 'border-blue-500/30',
      iconColor: 'text-blue-400'
    },
    praise: {
      icon: Star,
      gradient: 'from-green-500/20 to-green-600/5',
      border: 'border-green-500/30',
      iconColor: 'text-green-400'
    },
    tip: {
      icon: Lightbulb,
      gradient: 'from-yellow-500/20 to-yellow-600/5',
      border: 'border-yellow-500/30',
      iconColor: 'text-yellow-400'
    }
  };

  const { icon: Icon, gradient, border, iconColor } = config[insight.type];

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, x: -100, scale: 0.9 }}
      className={`bg-gradient-to-br ${gradient} border ${border} rounded-2xl p-4 relative group`}
    >
      {/* Dismiss Button */}
      <button
        onClick={() => onDismiss(insight.id)}
        className="absolute top-2 right-2 p-1.5 opacity-0 group-hover:opacity-100 hover:bg-white/10 rounded-lg transition-all"
      >
        <X className="w-4 h-4 text-white/40" />
      </button>

      <div className="flex gap-4">
        {/* Icon */}
        <div className={`w-10 h-10 rounded-xl bg-black/30 flex items-center justify-center shrink-0`}>
          <Icon className={`w-5 h-5 ${iconColor}`} />
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <p className="text-xs font-bold uppercase text-white/40 mb-1">
            {insight.title}
          </p>
          <p className="text-sm text-white/80 leading-relaxed">
            {insight.message}
          </p>

          {/* Action Link */}
          {insight.action && (
            <Link
              to={insight.action.href}
              className={`inline-flex items-center gap-1 mt-3 text-xs font-bold ${iconColor} hover:underline`}
            >
              {insight.action.label}
              <ChevronRight className="w-3 h-3" />
            </Link>
          )}
        </div>
      </div>
    </motion.div>
  );
}

// ══════════════════════════════════════════════════════════════════
// MAIN COMPONENT
// ══════════════════════════════════════════════════════════════════

interface NeuralFeedProps {
  salesData?: any[];
  maxItems?: number;
}

export default function NeuralFeed({ salesData = [], maxItems = 5 }: NeuralFeedProps) {
  const [insights, setInsights] = useState<NeuralInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());

  // Load insights on mount
  useEffect(() => {
    loadInsights();
  }, [salesData]);

  const loadInsights = async () => {
    setLoading(true);
    try {
      // Get audit logs for anomaly detection
      const auditLogs = await getRecentLogs(50);
      
      // Generate insights
      const newInsights = await generateDailyInsights(salesData, auditLogs);
      setInsights(newInsights);
    } catch (error) {
      console.error('[NeuralFeed] Failed to load insights:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleDismiss = (id: string) => {
    setDismissed(prev => new Set([...prev, id]));
  };

  const visibleInsights = insights
    .filter(i => !dismissed.has(i.id))
    .slice(0, maxItems);

  // Add context-based tips if no insights
  if (visibleInsights.length === 0 && !loading) {
    const context = getMenuContext();
    const contextTip: NeuralInsight = {
      id: 'context-tip',
      type: 'tip',
      severity: 'info',
      title: context.isWeekend ? 'Dica de Fim de Semana' : 'Dica do Dia',
      message: context.isWeekend 
        ? 'Fins de semana têm mais pedidos! Prepare o estoque e a equipe.'
        : context.timeOfDay === 'evening' 
        ? 'Horário de pico chegando! Confira se a cozinha está pronta.'
        : 'Tudo tranquilo por aqui. Que tal revisar o cardápio?',
      createdAt: new Date()
    };
    visibleInsights.push(contextTip);
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-primary/20 rounded-lg flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-primary" />
          </div>
          <div>
            <h3 className="font-bold text-sm">Neural Feed</h3>
            <p className="text-[10px] text-white/40">Powered by AI</p>
          </div>
        </div>

        <button
          onClick={loadInsights}
          disabled={loading}
          className="p-2 hover:bg-white/5 rounded-lg transition-colors disabled:opacity-50"
          title="Atualizar"
        >
          <RefreshCw className={`w-4 h-4 text-white/40 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* Insights List */}
      <div className="space-y-3">
        {loading ? (
          // Skeleton
          <div className="animate-pulse space-y-3">
            {[1, 2].map(i => (
              <div key={i} className="h-24 bg-white/5 rounded-2xl" />
            ))}
          </div>
        ) : (
          <AnimatePresence mode="popLayout">
            {visibleInsights.map(insight => (
              <InsightCard
                key={insight.id}
                insight={insight}
                onDismiss={handleDismiss}
              />
            ))}
          </AnimatePresence>
        )}
      </div>

      {/* Empty State */}
      {!loading && visibleInsights.length === 0 && (
        <div className="text-center py-8 text-white/40">
          <Sparkles className="w-8 h-8 mx-auto mb-2 opacity-40" />
          <p className="text-sm">Tudo em ordem por aqui! 👍</p>
        </div>
      )}
    </div>
  );
}
